changed train.py in a way so only test.yml fails

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,35 +7,32 @@ on:
       - completed
 
 jobs:
-  pull-and-run:
+  test:
     runs-on: windows-latest
 
-    env:
-      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Docker
-        uses: docker/login-action@v2
+      - name: Check train.yml status
+        id: check_train_status
+        uses: actions/github-script@v4
         with:
-          username: ${{ env.DOCKER_USERNAME }}
-          password: ${{ env.DOCKER_PASSWORD }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const payload = context.payload;
+            const status = payload.workflow_run.conclusion;
+            return status;
+      - name: Triggered by train.yml
+        if: steps.check_train_status.outputs.status == 'success'
+        run: echo "Train workflow passed, proceeding with tests."
 
-      - name: Pull Docker image
+      - name: Triggered by train.yml
+        if: steps.check_train_status.outputs.status == 'failure'
         run: |
-          docker pull ${{ env.DOCKER_USERNAME }}/cicd-model:1.0
-
-      - name: Run tests
-        id: test
+          echo "Train workflow failed, so not proceeding"
+          exit 1
+      - name: Run tests and check score
+        if: steps.check_train_status.outputs.status == 'success'
         run: |
           OUTPUT=$(docker run --rm ${{ env.DOCKER_USERNAME }}/cicd-model:1.0 python test.py)
           echo "Score:"
           echo "$OUTPUT"
-          if (( $(echo "$OUTPUT > 0.35" | bc -l) )); then
-            echo "Sufficient Accuracy"
-          else
-            echo "Insufficient Accuracy" && exit 1
-          fi    
+          if [[ $(echo "$OUTPUT > 0.35" | bc -l) == 1 ]]; then echo "Sufficient Accuracy"; else echo "Insufficient Accuracy" && exit 1; fi
